### ISSUE TITLE
Add Japanese

### ISSUE THREAD

**Issue by fu-sen** [djemos/sli#2]
How many years ago? I provided a Japanese translation of her Salix.
SalixLive 15.0 has not been officially released yet, so providing the Japanese translation now may be in time for the addition of SalixLive 15.0.

- You may have noticed that I applied to add Japanese to Transifex.
- Or I can pull request the .po file directly.

One question: I was wondering if I should use `ja` or `ja_JP`. Since the locale is `ja_JP.UTF-8`, it will probably be `ja_JP`.

I know you're a Slackel developer, so I'll do the same for Slackel. However, since we can predict that SalixLive will be released soon, I think we need to give priority to Salix.

**Comment by fu-sen** [comment]
I'm ready to pull request the .po file:
![VirtualBox_Salix_10_11_2022_15_34_30](https://user-images.githubusercontent.com/5434159/201018506-d0fe24de-95e3-489e-9d75-6f70793fa1da.png)

**Comment by djemos** [comment]
ja_JP is OK.  Thanks.

**Comment by fu-sen** [comment]
Thanks for merging #3. Already posted on the Salix forums, but this issue should be enough to close.
